### ISSUE TITLE
[Bug]: File Not Found Error

### ISSUE THREAD

**Issue by vsolaz-robotnik** [RobotnikAutomation/rcomponent#28]
### What happened?

Solved by adding:
```py
from test_package.test import Test
```
Instead of:
```py
from test import Test
```
In `test_node.py`.

### Relevant log output

```shell
robot@oasees:~/catkin_ws/devel$ roslaunch test_package test.launch 
... logging to /home/robot/.ros/log/616b967e-48cb-11ef-961f-4b2af4126970/roslaunch-oasees-235967.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://oasees:36631/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /test/desired_freq: 1.0
 * /test/example_subscriber_name: example

NODES
  /
    test (test_package/test_node.py)

auto-starting new master
process[master]: started with pid [235975]
ROS_MASTER_URI=http://oasees:11311

setting /run_id to 616b967e-48cb-11ef-961f-4b2af4126970
process[rosout-1]: started with pid [235985]
started core service [/rosout]
process[test-2]: started with pid [235988]
Traceback (most recent call last):
  File "/home/robot/catkin_ws/devel/lib/test_package/test_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/robot/catkin_ws/src/test_package/src/test_package/test_node.py", line 5, in <module>
    from test import Test
ImportError: cannot import name 'Test' from 'test' (/home/robot/catkin_ws/devel/.private/test_package/lib/test_package/test.py)
[test-2] process has died [pid 235988, exit code 1, cmd /home/robot/catkin_ws/devel/lib/test_package/test_node.py __name:=test __log:=/home/robot/.ros/log/616b967e-48cb-11ef-961f-4b2af4126970/test-2.log].
log file: /home/robot/.ros/log/616b967e-48cb-11ef-961f-4b2af4126970/test-2*.log
```

**Comment by vsolaz-robotnik** [comment]
The solution doesn't work if the package and the file are named the same:

```shell
robot@oasees:~/catkin_ws$ roslaunch test_package test_package.launch 
... logging to /home/robot/.ros/log/bae33b52-48d1-11ef-961f-4b2af4126970/roslaunch-oasees-326685.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://oasees:43399/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /test_package/desired_freq: 1.0
 * /test_package/example_subscriber_name: example

NODES
  /
    test_package (test_package/test_package_node.py)

auto-starting new master
process[master]: started with pid [326693]
ROS_MASTER_URI=http://oasees:11311

setting /run_id to bae33b52-48d1-11ef-961f-4b2af4126970
process[rosout-1]: started with pid [326703]
started core service [/rosout]
process[test_package-2]: started with pid [326706]
Traceback (most recent call last):
  File "/home/robot/catkin_ws/devel/lib/test_package/test_package_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/robot/catkin_ws/src/test_package/src/test_package/test_package_node.py", line 5, in <module>
    from test_package.test_package import TestPackage
ModuleNotFoundError: No module named 'test_package.test_package'; 'test_package' is not a package
[test_package-2] process has died [pid 326706, exit code 1, cmd /home/robot/catkin_ws/devel/lib/test_package/test_package_node.py __name:=test_package __log:=/home/robot/.ros/log/bae33b52-48d1-11ef-961f-4b2af4126970/test_package-2.log].
log file: /home/robot/.ros/log/bae33b52-48d1-11ef-961f-4b2af4126970/test_package-2*.log
```
